### PR TITLE
Fix image embeds

### PR DESCRIPTION
**Pull request by resynth1943**
These don't work at all in GFM, and this fixes that :-)

### CODE REVIEW

**Comment by Rudd-O** [comment]
Didn't work.  Hm.

**Comment by Rudd-O** [comment]
I think the embeds have stopped working on Github.  I tried your PR and the baseline PR, both of them comply with the https://guides.github.com/features/mastering-markdown/ guide, and it didn't work in either case.

**Comment by resynth1943** [comment]
I did mark it as a draft for a reason :stuck_out_tongue:

**Comment by resynth1943** [comment]
@Rudd-O a sneaking suspicion is that the spaces in the file name is causing this. Perhaps GFM doesn't support it, but I'm not entirely sure.

**Comment by Rudd-O** [comment]
It *used* to work!  This is so disappointing.  It's 2020, why can't they support spaces in file names?  It's like not supporting Unicode.

Would you mind finding out where the GFM repo is?  I'd like to report an issue (though I suspect it'll be rejected for "reasons").

**Comment by resynth1943** [comment]
@Rudd-O I was right, and replacing the spaces with `%20` does fix it *for GitHub.*
However, I'll submit a PR that uses hyphens instead, as I'm not sure how my little hack would work on other readers.

**Comment by resynth1943** [comment]
> Would you mind finding out where the GFM repo is?

Sure :-)

**Comment by resynth1943** [comment]
So it looks like this issue doesn't strictly pertain to GFM.
It's also present in [VSCode](https://github.com/Microsoft/vscode/issues/7871), [markdown-it](https://github.com/markdown-it/markdown-it/issues/147) and [the Commonmark spec](http://spec.commonmark.org/0.21/#link-destination).

I couldn't find a repo for GFM, but perhaps GitHub's Support site (or [feature request form](https://support.github.com/contact/feedback)) would be a better match? Not 100% sure on that one.

Today, we learned something. Hmm. Feel free to contact me on Matrix, I don't like using this as an instant messenger.

**Comment by Rudd-O** [comment]
Can you issue a PR or an update that uses %20's to replace the spaces?  This might work.

**Comment by Rudd-O** [comment]
Matrix: @ruddo:matrix.org ping me there please.

**Comment by Rudd-O** [comment]
(L
owercase.  Apparently GFM also uppercases Twitter-style handles because it doesn't understand handles aren't necessarily Twitter or Github.)

**Pull request merged**
