### PR TITLE
create firewall rules for incoming traffic

### PR DESCRIPTION
**Pull request by lamuse**
Hi, great work, Rudd-O!
I added some code to create iptables rules for incoming traffic once the firewall settings of the target VM are changed. my code is GPL.

regards
lamuse

### CODE REVIEW

**Comment by jpouellet** [comment]
Are you aware of `from-*` rule syntax?

**Comment by jpouellet** [comment]
This is not the correct way to fix it, since you do not distinguish between inbound & outbound rules, and duplicate a bunch of rule-formatting code (which is now in triplicate).

See https://github.com/jpouellet/qubes-network-server/commit/7dc5faf02e1d8da286452d5cf26ca474c32d1a1b (in #3) for what I think is a better way.

**Comment by Rudd-O** [comment]
Hi there -- did I understand correctly that this code changes behavior so that a rule with address X netmask Y port W allows traffic **in** and **out** of the VM from/to address X?

If that is the case, then this is not going to make it into the code, because the idea behind the existing code is to have rules separate for inbound (syntax `from-<address>`) and outbound (regular Qubes syntax), and this code would break that behavior.

**Comment by Rudd-O** [comment]
Unfortunately we had to drop support for firewall rules management in the release for 4.0 (sorry!).  I look forward to improvements in the Qubes agent to support such things in the future.  In the meantime, the to-do list in the repo contains a line item to re-add support for chaining ProxyVMs and managing their inbound rules.

**Comment by tlaurion** [comment]
@Rudd-O can you detail what is missing for Qubes agent and firewall rules being possible to add from the GUI and netvm chaining so others can jump in? The README should be modified accordingly.

Awesome that you updated that awesome tool!! Now can't wait to expose ports from a VPN proxyvm!

**Comment by Rudd-O** [comment]
So, two things:

(1)

The previous code "hacked" `qubes-firewall` at runtime to support rules with `from-` prefixes.  This proved very hard to maintain, so I pulled that code out (it's still in the `release-3.2` branch).

The correct thing to do here is to extend the admin core so that a rule can specify its direction, and a compatible change to `qubes-firewall` on the agent side does the right thing.

At the moment Qubes network server doesn't do anything special to the forwarding rules — except for allowing VIF-to-VIF traffic — because the default for ProxyVMs is to forward traffic to their connected VMs.

(2)

The previous code also did an ungodly thing that the current code does not do: it recursed through the connected VMs to add routes and rules for the specific IP/VIF.

It did so in a very poor way (really only supporting this behavior upon NetVM/ProxyVM domain start).  

Fundamentally what happened if you had a Net->Proxy->App chain, the previous code would walk that path from Net to App, and would add on each running domain hard-coded routes / firewall rules to the IP/VIF assigned to the App, so that traffic coming in from outside the Net would know which interface to send the traffic to, along each hop, all the way up to the App .

This should be relatively easy to re-do now that we have an admin core extension to inform the running domains of what's actually up.  At the moment, the admin core code assumes that only the NetVM to which the AppVM is attached to, needs to know that there's an IP which needs routing.  This is the fundamental source of the current limitation that forces you to attach your networked AppVM to the NetVM instead of to a ProxyVM.  That IP information should instead probably be fanned down the chain from AppVM to final NetVM, so that each VM along the path knows where to route the traffic, and sets the correct routes.

**Comment by Rudd-O** [comment]
This should probably be discussed more at-length in an issue, not in a PR.  Feel free to summarize the convo in an open ticket so we can track it and discuss design.

**Comment by tlaurion** [comment]
Should be done conjointly with @mamarek with t text above, no?

**Comment by Rudd-O** [comment]
Yes please.

**Pull request closed without merging**
